<a href="https://colab.research.google.com/github/Fernanda-Mesa/Clase06_IA/blob/main/Clase06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**3.3. Checking for Missing Data**

In [1]:
import pandas as pd
import numpy as np

**Missing Value**

In [2]:
pd.Series(['Male','Female','Male','Male','Female','Female','Female'])

0      Male
1    Female
2      Male
3      Male
4    Female
5    Female
6    Female
dtype: object

In [3]:
pd.Series(['Male','Female','Male','Male','Female','Female','Female'],index=['a','b','c','d','e','f','g'])

a      Male
b    Female
c      Male
d      Male
e    Female
f    Female
g    Female
dtype: object

In [4]:
pd.Series(np.array(['Male', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female']))

0      Male
1    Female
2      Male
3      Male
4    Female
5    Female
6    Female
dtype: object

In [5]:
ser=pd.Series(np.array(['Male', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female']))
print(ser)

0      Male
1    Female
2      Male
3      Male
4    Female
5    Female
6    Female
dtype: object


In [6]:
type(ser)

pandas.core.series.Series

In [7]:
dict_data={'a':1,'b':2,'c':3,'d':4}

In [8]:
pd.Series(dict_data)

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
ser1=pd.Series(dict_data)
print(ser1)

a    1
b    2
c    3
d    4
dtype: int64


In [10]:
type(ser1)

pandas.core.series.Series

In [11]:
ser1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [12]:
ser1.values

array([1, 2, 3, 4])

In [13]:
list_data=['2019-01-02', 3.14, 'ABC', 100, True]

In [14]:
ser2 = pd.Series(list_data)
print(ser2)

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object


In [15]:
ser2.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
pd.DataFrame({"Name": ["Braund, Mr, Owen Harries",
                       "Allen, Mr. William Henry",
                       "Bonnel, Miss. Elizabeth"],
              "Age": [22, 35, 58],
              "Sex": ["male", "make", "female"]})

Name  Age     Sex
0  Braund, Mr, Owen Harries   22    male
1  Allen, Mr. William Henry   35    make
2   Bonnel, Miss. Elizabeth   58  female

In [17]:
df=pd.DataFrame({"Name": ["Braund, Mr, Owen Harries",
                       "Allen, Mr. William Henry",
                       "Bonnel, Miss. Elizabeth"],
              "Age": [22, 35, 58],
              "Sex": ["male", "make", "female"]})

In [18]:
df['Age']

0    22
1    35
2    58
Name: Age, dtype: int64

In [19]:
type(df['Age'])

pandas.core.series.Series

In [20]:
df['Age'][0]

22

In [21]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,0]])

In [22]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [23]:
df[0]

0    1
1    4
2    7
Name: 0, dtype: int64

In [24]:
type(df[0])

pandas.core.series.Series

In [25]:
eye = pd.Series({'Brown':220, 'Blue':215, 'Hazel':93, 'Green':64})

In [26]:
print(eye)

Brown    220
Blue     215
Hazel     93
Green     64
dtype: int64


In [27]:
eye.index

Index(['Brown', 'Blue', 'Hazel', 'Green'], dtype='object')

In [28]:
print(eye.index)

Index(['Brown', 'Blue', 'Hazel', 'Green'], dtype='object')


In [29]:
type(eye)

pandas.core.series.Series

In [30]:
eye.name

In [31]:
eye.name = "eye_color"

In [32]:
print(eye.name)

eye_color


In [33]:
print(eye.values)

[220 215  93  64]


In [34]:
print(eye.sort_values())

Green     64
Hazel     93
Blue     215
Brown    220
Name: eye_color, dtype: int64


In [35]:
print(eye.sort_index())

Blue     215
Brown    220
Green     64
Hazel     93
Name: eye_color, dtype: int64


In [36]:
print(eye.sort_index(ascending=False))

Hazel     93
Green     64
Brown    220
Blue     215
Name: eye_color, dtype: int64


In [37]:
print(eye.unique())

[220 215  93  64]


In [38]:
print(eye.nunique())

4


In [39]:
my_data2=[220, 215, 93, 64, 64]

In [40]:
eye2=pd.Series(data=my_data2, index=['Brown', 'Blue', 'Blue', 'Hazel', 'Green'])

In [41]:
print(eye2)

Brown    220
Blue     215
Blue      93
Hazel     64
Green     64
dtype: int64


In [42]:
print(eye2.unique())

[220 215  93  64]


In [43]:
print(eye2.nunique())

4


In [44]:
print(eye2.value_counts())

64     2
220    1
215    1
93     1
Name: count, dtype: int64


In [45]:
ser = pd.Series([0,10,20,30,40], index=['a','b','c','d','e'])

In [46]:
ser[1]

10

In [47]:
ser['b']

10

In [48]:
ser[0:3]

a     0
b    10
c    20
dtype: int64

In [49]:
ser1=pd.Series([0,1,2,3,4], index=[0,1,2,3,4])
ser2=pd.Series([0,1,2,3,4], index=[4,3,2,1,0])

In [50]:
ser1

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [51]:
ser2

4    0
3    1
2    2
1    3
0    4
dtype: int64

In [52]:
ser1+ser2

0    4
1    4
2    4
3    4
4    4
dtype: int64

In [53]:
ser1*ser2

0    0
1    3
2    4
3    3
4    0
dtype: int64

In [54]:
ser1/ser2

0    0.000000
1    0.333333
2    1.000000
3    3.000000
4         inf
dtype: float64

In [55]:
ser1.sum()

10

In [56]:
ser1.mean()

2.0

In [57]:
ser1.median()

2.0

In [58]:
ser1.min()

0

In [59]:
ser1.std()

1.5811388300841898

In [60]:
ser1.sort_values()

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [61]:
ser_height = pd.Series([160,170,180],name='height')

In [62]:
plus_10 = lambda x:x+10

In [63]:
plus_10(5)

15

In [64]:
ser_height.apply(lambda x:x+10)

0    170
1    180
2    190
Name: height, dtype: int64

**LIBRERIA SEABORN: Sirve para datasets y visualizaciones de datos (graficas), similar a matplotlib. Incluye datos automaticos, para llegar y usar sin descar los datos.**
En el caso de que se tengan que descargar los datos, se utilizará la libreria pandas.
Es mucho mas bonito cuando se usa para R, similar a ggplot2.

Al formatear matplotlib se puede llegar a un estilo de ggplot2 (que es más bonito). Esto tiene un codigo integrado.

La gente que hace procesamiento de datos, generalmente usa más R.

In [65]:
import seaborn as sns

In [67]:
titanic = sns.load_dataset("titanic") #Se utilizará solo para cargar el archivo.

In [69]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

##**Pandas Series and DataFrame Practice**

In [73]:
pd.read_csv('data_Iris.csv')

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [74]:
iris_df = pd.read_csv('data_Iris.csv')

In [75]:
type(iris_df)

pandas.core.frame.DataFrame

In [76]:
data={'NAME':['Jake','Jeniffer','Paul','Andrew'], 'AGE':[24,21,25,19], 'GENDER':['M','F','M','M']}

In [77]:
print(data)

{'NAME': ['Jake', 'Jeniffer', 'Paul', 'Andrew'], 'AGE': [24, 21, 25, 19], 'GENDER': ['M', 'F', 'M', 'M']}


In [78]:
pd.DataFrame(data)

NAME  AGE GENDER
0      Jake   24      M
1  Jeniffer   21      F
2      Paul   25      M
3    Andrew   19      M

In [79]:
df = pd.read_csv('https://raw.githubusercontent.com/davidlealo/sic_ai_2024/main/002_preprocesamiento/Chapter_3/data_studentlist.csv')

In [80]:
df

name gender  age  grade absence bloodtype  height  weight
0      Jared Diamond      M   23      3       Y         O   165.3    68.2
1     Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2       Brian Martin      M   24      4       N         B   175.0    80.1
3       David Hassel      M   23      3       N        AB   182.1    85.7
4    Clara Rodriquez      F   20      1       Y         A   168.0    49.5
5   Jennifer Lorentz      F   21      2       N         O   162.0    52.0
6        Susan Clark      F   22      1       N         O   155.2    45.3
7    Margareth Jones      F   23      1       N         A   176.9    55.0
8       John Bertsch      M   23      3       N         B   178.5    64.2
9     Jake Timmerman      M   22      2       N         B   176.1    61.3
10     Joshua Connor      M   24      4       Y         O   167.1    62.0
11      John Matsuda      M   22      2       N        AB   180.0    75.8
12      Eddy Johnson      M   21      1       N         A   162.2    55.3
13  Rebecah Anderson      F   23      3       N         O   176.1    53.1
14      Linda Carter      F   22      2       N         B   158.2    45.2
15    Richard Swayze      M   24      4       Y         B   168.6    70.2
16       Andrew King      M   21      1       N         A   169.2    62.2

In [81]:
df.head(15)

name gender  age  grade absence bloodtype  height  weight
0      Jared Diamond      M   23      3       Y         O   165.3    68.2
1     Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2       Brian Martin      M   24      4       N         B   175.0    80.1
3       David Hassel      M   23      3       N        AB   182.1    85.7
4    Clara Rodriquez      F   20      1       Y         A   168.0    49.5
5   Jennifer Lorentz      F   21      2       N         O   162.0    52.0
6        Susan Clark      F   22      1       N         O   155.2    45.3
7    Margareth Jones      F   23      1       N         A   176.9    55.0
8       John Bertsch      M   23      3       N         B   178.5    64.2
9     Jake Timmerman      M   22      2       N         B   176.1    61.3
10     Joshua Connor      M   24      4       Y         O   167.1    62.0
11      John Matsuda      M   22      2       N        AB   180.0    75.8
12      Eddy Johnson      M   21      1       N         A   162.2    55.3
13  Rebecah Anderson      F   23      3       N         O   176.1    53.1
14      Linda Carter      F   22      2       N         B   158.2    45.2

In [82]:
df.groupby(['gender','bloodtype'])['height'].mean()

gender  bloodtype
F       A            172.450000
        AB           170.100000
        B            158.200000
        O            164.433333
M       A            165.700000
        AB           181.050000
        B            174.550000
        O            166.200000
Name: height, dtype: float64

In [83]:
my_dict = {"Size":["L", "L", "M", "M", "M", "S", "S", "S", "S"],
           "Type":["A", "A", "A", "B", "B", "A", "A", "B", "B"],
           "Location":["L1", "L1", "L1", "L2", "L2", "L1", "L2", "L2", "L1"],
           "A":[1, 2, 2, 3, 3, 4, 5, 6, 7],
           "B":[2, 4, 5, 5, 6, 6, 8, 9, 9]}
df = pd.DataFrame(my_dict)
df

Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [84]:
dfr = pd.pivot_table(df, index=['Size','Type'], columns='Location', values='B')

In [85]:
dfr

Location    L1   L2
Size Type          
L    A     3.0  NaN
M    A     5.0  NaN
     B     NaN  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [86]:
dfr.sum(axis=0)

Location
L1    23.0
L2    22.5
dtype: float64

In [87]:
dfr.sum(axis=1)

Size  Type
L     A        3.0
M     A        5.0
      B        5.5
S     A       14.0
      B       18.0
dtype: float64

In [88]:
dfr.mean(axis=0, skipna=False)

Location
L1   NaN
L2   NaN
dtype: float64

In [89]:
dfr.mean(axis=0, skipna=True)

Location
L1    5.75
L2    7.50
dtype: float64

In [90]:
dfr.describe()

Location    L1        L2
count     4.00  3.000000
mean      5.75  7.500000
std       2.50  1.802776
min       3.00  5.500000
25%       4.50  6.750000
50%       5.50  8.000000
75%       6.75  8.500000
max       9.00  9.000000

In [91]:
dfr.count(axis=0) #cuenta los valores no nulos

Location
L1    4
L2    3
dtype: int64

In [92]:
df.A.corr(df.B) #correlación

0.9594032236002469

In [93]:
dfr.corr() #correlación

Location   L1   L2
Location          
L1        1.0  1.0
L2        1.0  1.0

In [94]:
#df.corrwith(df.A)