<a href="https://colab.research.google.com/github/Fernanda-Mesa/InteligenciaArtificial_MachineLearning/blob/main/Clase04IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tipo de arreglo de datos, desde un numero hasta otro numero.**

In [1]:
import numpy as np

**ALGORITMOS DE CADENA**

In [2]:
cadena_numero = "1"
print(cadena_numero+cadena_numero)

11


In [3]:
int(cadena_numero)+int(cadena_numero)

2

**ARREGLOS DE DATOS**

In [4]:
arrango = np.arange(10,20,2)
print(arrango)

[10 12 14 16 18]


**ARRANGO es similar que array pero con algunas diferencias...**

In [5]:
arrango = np.arange(10,20,2)
print(arrango)

[10 12 14 16 18]


In [6]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [7]:
A = np.linspace(10,20,5)
print(A)

[10.  12.5 15.  17.5 20. ]


In [8]:
a = arrango+arrango
print(a)

[20 24 28 32 36]


In [9]:
a1 = arrango*arrango
print(a1)

[100 144 196 256 324]


In [10]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [11]:
arr1 = np.array([5,6,7,8,9])
print(arr1)

[5 6 7 8 9]


In [12]:

arr2 = np.array((1,2,3,4,5))
print(arr2)

[1 2 3 4 5]


In [13]:
arr3 = np.array({'a':1, 'b':2, 'c':3})
print(arr3)

{'a': 1, 'b': 2, 'c': 3}


In [14]:
arr5 = np.arange(5)
print(arr5)

[0 1 2 3 4]


In [15]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
b = np.arange(1,10)
print(b)

[1 2 3 4 5 6 7 8 9]


In [17]:
c = np.arange(2,101,2)
print(c)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [18]:
d = np.arange(1,101,2)
print(d)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [19]:
e = np.arange(1,100,2,dtype=float)
print(e)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49. 51. 53. 55. 57. 59. 61. 63. 65. 67. 69. 71.
 73. 75. 77. 79. 81. 83. 85. 87. 89. 91. 93. 95. 97. 99.]


In [20]:
f = np.arange(1.3,100,2.9,dtype=float)
print(f)

[ 1.3  4.2  7.1 10.  12.9 15.8 18.7 21.6 24.5 27.4 30.3 33.2 36.1 39.
 41.9 44.8 47.7 50.6 53.5 56.4 59.3 62.2 65.1 68.  70.9 73.8 76.7 79.6
 82.5 85.4 88.3 91.2 94.1 97.  99.9]


# **Clase 3: Introducción a Pandas y Nunpy**

Bibliotecas fundamentales para la manipulación y análisis de datos en Python: Pandas y NumPy.

## **NumPy**

**NumPy** (Numerical Python) es una biblioteca que proporciona soporte para crear y manipular matrices grandes y multidimensionales, junto con una colección de funciones matemáticas para operar con estas matrices de manera eficiente.

###**Características principales de NumPy:**

Arrays multidimensionales: NumPy proporciona una estructura de datos llamada ndarray, que permite manejar matrices de cualquier dimensión.
Funciones matemáticas: Incluye funciones para operaciones algebraicas, estadísticas y lógicas.
Interoperabilidad: Funciona bien con otras bibliotecas como SciPy y Matplotlib.

##**Pandas**

Pandas es una biblioteca que proporciona estructuras de datos y herramientas de análisis de datos flexibles y eficientes. Es especialmente útil para datos tabulares, como los que se encuentran en hojas de cálculo o bases de datos.

###**Características principales de Pandas:**

Series: Estructura unidimensional similar a una lista o un array de NumPy.
DataFrame: Estructura bidimensional similar a una tabla en una base de datos o una hoja de cálculo de Excel.
Funciones de E/S: Herramientas para leer y escribir datos en diversos formatos (CSV, Excel, SQL, etc.).
Manipulación de datos: Funciones para filtrar, agrupar, pivotar, fusionar, etc.

**ARRAY MULTIDIMENCIÓN**

**EJEMPLOS BÁSICOS DE COMO USAR NUMPY.**

In [21]:
# Crea un array unidimensional
array_1d = np.array([1, 2, 3, 4, 5])
print("Array unidimensional:", array_1d)

Array unidimensional: [1 2 3 4 5]


In [22]:
# Crea un array bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array bidimensional:\n", array_2d)

Array bidimensional:
 [[1 2 3]
 [4 5 6]]


In [23]:
x = np.array([[0,1,2,3,4],[5,6,7,8,9]], dtype=int) #arreglo binario
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
print(x.ndim) #dimensión

2


In [25]:
print(x.shape) #forma

(2, 5)


In [26]:
print(x.size) #tamaño

10


In [27]:
print(x,type(x)) #tipo de dato del array

[[0 1 2 3 4]
 [5 6 7 8 9]] <class 'numpy.ndarray'>


In [28]:
print(x.dtype) #tipo de dato del array

int64


**Volviendo al arreglo bidimensional array, guardado de la forma arr_2d.**

In [29]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) #arreglo binimensional
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [30]:
print(arr_2d.ndim) #dimensión

2


In [31]:
print(arr_2d.shape) #forma

(2, 3)


In [32]:
print(arr_2d.size) #tamaño

6


In [33]:
print(arr_2d.dtype) #tipo de dato del array

int64


In [34]:
# Operaciones básicas dos dimensiones
print("Suma de todos los elementos:", np.sum(array_2d))
print("Media de los elementos:", np.mean(array_2d))
print("Máximo valor:", np.max(array_2d))

Suma de todos los elementos: 21
Media de los elementos: 3.5
Máximo valor: 6


In [35]:
np.zeros(5, dtype=int) #arreglos de ceros

array([0, 0, 0, 0, 0])

In [36]:
np.ones(5, dtype=int) #arreglos de unos

array([1, 1, 1, 1, 1])

In [37]:
np.ones(5, dtype=float) #arreglos de unos

array([1., 1., 1., 1., 1.])

In [38]:
np.ones(5, dtype=bool)

array([ True,  True,  True,  True,  True])

In [39]:
np.ones(5, dtype = None) #arreglos de none

array([1., 1., 1., 1., 1.])

In [40]:
np.ones((3,4), dtype=int) #arreglos de unos

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
np.ones((3,4), dtype=float) #arreglos de unos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
arr_2d_zeros = np.zeros((3, 4)) #arreglo de ceros
print(arr_2d_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [43]:
arr_2d_zeros_int = np.zeros((3, 4), dtype=int) #arreglo de ceros enteros
print(arr_2d_zeros_int)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [44]:
print(len(arr_2d_zeros))
print(len(arr_2d_zeros_int))
print(len(arr_2d))

print(len(array_1d))

print(len(x))

print(len(arr5))
print(arr5.size)

3
3
2
5
2
5
5


In [45]:
print(type(1))

<class 'int'>


In [46]:
print(type(1.0))

<class 'float'>


In [47]:
numero = input("Ingrese un numero: ")
print(numero)
print(type(numero))
print(type(int(numero)))

Ingrese un numero: 

<class 'str'>


ValueError: invalid literal for int() with base 10: ''

In [ ]:
var1 = np.ones(5, dtype=int) #arreglos de unos

In [ ]:
print(type(var1)) #tipo de dato del array

In [ ]:
var2 = (1,2,3,4,5) #tupla
print(type(var2))

**Podemos darnos cuenta de que aun es una tupla dado que no cambio su situación, su función al aplicar el numpy. Por lo tanto se puede nodificar de la siguiente forma:**

In [48]:
var2 = np.array(var2)
print(type(var2))

NameError: name 'var2' is not defined

In [49]:
var3 = (1,10)
print(type(var3))
print(type(np.array(var3)))

<class 'tuple'>
<class 'numpy.ndarray'>


In [75]:
y1 = np.reshape(np.array(var3),(1,2)) #reshape
print(y1)

[[ 1 10]]


In [51]:
y2 = np.reshape(np.arange(2*3*4),(2,3,4)) #reshape
print(y2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [77]:
y1.strides #strides}

(16, 8)

In [78]:
y2.strides #strides

(96, 32, 8)

In [53]:
x = np.array([[0,1,2,3,4],[5,6,7,8,9]], dtype=np.int32) #arreglo binario
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [54]:
x.strides #strides

(20, 4)

**NUMEROS ALEATORIOS.**

Numpy proporciona funciones para generar numero aleatrorios.

In [55]:
# Generar datos que siguen una distribución normal estándar (media 0, desviación estándar 1)
random_data = np.random.randn(5)
print("Datos aleatorios:", random_data)

Datos aleatorios: [ 1.28940249  1.28323406  0.10854211  0.71755257 -1.06494266]


In [56]:
# Crear un array 2D de 100×100 con números aleatorios
data2 = np.random.randn(100, 100)
print("Datos aleatorios:\n", data2)
print( "Forma del array 2D:", data2.shape)

Datos aleatorios:
 [[ 1.18222252 -0.89142878  0.24703059 ... -0.88710671  1.97592941
   0.11587712]
 [-0.70820119 -0.04890105  0.39978229 ...  0.62404631 -0.74918836
  -0.32626245]
 [-0.74148098  1.10653658  0.14642222 ...  0.46012177 -0.91720862
   0.09740151]
 ...
 [-0.95505541  2.21353378 -1.16019867 ...  1.72090304 -0.68618942
   0.3079041 ]
 [-0.8027211  -0.06557867 -0.35098422 ... -0.39757596 -1.20374844
   0.57886303]
 [-1.0159707   0.59052698  0.88612126 ... -0.50982913 -1.63960616
  -0.95396434]]
Forma del array 2D: (100, 100)


###**COMPARACIÓN DE RENDIMIENTO ENTRE LISTAS Y ARRAYS.**

Se comparará el rendimiento de una lista de Python y un array de Numpy al almacenar y operar con un millón de enteros.

In [57]:
import time

In [58]:
#Crear un array Numpy de 1 millón de elementos
np_array = np.arange(1000000)

In [59]:
#Crear una lista de Python de 1 millón de elementos
python_list = list(range(1000000))

In [60]:
#Función para medir el tiempo de ejecución
def measure_time(func, *args, **kwargs):
    start = time.time()
    result = func(*args, **kwargs)
    end = time.time()
    return result, end - start

In [61]:
#Función para medir el tiempo de ejecución
def time_execution(func):
    start = time.time()
    func()
    end = time.time()
    return end - start

In [62]:
#Operación con Numpy
def numpy_operation():
  return np_array * 2

#Medir tiempo para Numpy
numpy_time = time_execution(numpy_operation)
print(f"Tiempo de ejecución para Numpy:{numpy_time:.5f} segundos")

Tiempo de ejecución para Numpy:0.00469 segundos


In [63]:
#Operación con lista de Python
def python_list_operation():
  return [x*2 for x in python_list]

#Medir tiempo para lista de Python
python_time = time_execution(python_list_operation)
print(f"Tiempo de ejecución para lista de Python:{python_time:.5f} segundos")

Tiempo de ejecución para lista de Python:0.11202 segundos


In [64]:
# Calcular la diferencia de velocidad
speed_difference = python_time / numpy_time
print(f"NumPy es aproximadamente {speed_difference:.2f} veces más rápido")

NumPy es aproximadamente 23.87 veces más rápido


#**Operaciones Avanzadas con NumPy**

###Reshaping (Cambio de Forma) El reshaping permite cambiar la forma de un array sin modificar sus datos.


In [65]:
# Crear un array unidimensional
ar = np.arange(12)
print("Array original:", ar)

Array original: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [79]:
# Reshape a 3x4
reshaped_ar = ar.reshape(3,4)
print("Array con nueva forma (3x4):")
print(reshaped_ar)

Array con nueva forma (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [81]:
# Reshape a 3x4
reshaped_ar = np.reshape(np.arange(12), (3,4))
print("Array con nueva forma (3x4):")
print(reshaped_ar)

Array con nueva forma (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [82]:
# Cambiar la forma directamente
ar.shape = (2, 6)
print("Array con forma cambiada (2x6):")
print(ar)

Array con forma cambiada (2x6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


##**Explicación de la Diferencia de Rendimiento**

**Vectorización:** NumPy utiliza operaciones vectorizadas, que son mucho más rápidas que los bucles en Python puro.

**Implementación en C:** Las operaciones de NumPy están implementadas en C, lo que las hace más rápidas que el código Python interpretado. Optimización de memoria: NumPy utiliza arrays contiguos en memoria, lo que mejora la eficiencia de acceso a los datos.

**Tipos de datos homogéneos:** Los arrays de NumPy contienen elementos del mismo tipo, lo que permite optimizaciones adicionales.

Operaciones Adicionales con Arrays de NumPy Agregar Elementos a Arrays de NumPy

In [83]:
# Agregar un valor a un array unidimensional
arr_e = np.array([1, 2, 3, 4, 5])
new_arr = np.append(arr_e, 6)
print("Array con nuevo elemento:", new_arr)

# Agregar elementos a un array bidimensional
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
new_row = np.array([[7, 8, 9]])
new_arr_2d = np.append(arr_2d, new_row, axis=0)
print("Array 2D con nueva fila:")
print(new_arr_2d)

Array con nuevo elemento: [1 2 3 4 5 6]
Array 2D con nueva fila:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


###**Eliminar Elementos de Arrays de NumPy**

In [84]:
# Eliminar un elemento de un array unidimensional
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.delete(arr, 2)  # Elimina el elemento en el índice 2
print("Array con elemento eliminado:", new_arr)

# Eliminar una fila de un array bidimensional
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_arr_2d = np.delete(arr_2d, 1, axis=0)  # Elimina la segunda fila
print("Array 2D con fila eliminada:")
print(new_arr_2d)

Array con elemento eliminado: [1 2 4 5]
Array 2D con fila eliminada:
[[1 2 3]
 [7 8 9]]


#**TAREA 2. NUMPY**

```
# Esto tiene formato de código
```

**Hacer ejemplos similares al título de Reshaping y números aleatorios explicando los resultados en un comentario o en markdown. Puede ser un ejemplo muy parecido, con otros números, pero con explicaciones propias de usted.

Enviar a mi correo**



**PARTE A**

In [85]:
#CREAR UN ARRAY UNIDIMENSIONAL.

arr0 = np.arange(11)
print("Array original", arr0)

arr_a = np.arange(0,11,1)
print("Array original", arr_a)

Array original [ 0  1  2  3  4  5  6  7  8  9 10]
Array original [ 0  1  2  3  4  5  6  7  8  9 10]


**Aparecen los numero hasta el 10 porque al escribir el 11 es el limite o stop de la función. Los numeroS son consecutivos porque no cuenta con saltos. Si contara con saltos seria de la siguiente forma:**

In [86]:
arr_b = np.arange(0,11,2)
print("Array original", arr_b)

Array original [ 0  2  4  6  8 10]


**Donde se puede observar los saltos de dos en dos, desde el primer valor inicial, cero puesto en el parentesis, seguido por el numero penultimo y su salto.**

**PARTE B.**

In [87]:
arr = np.arange(20)
print("Array original", arr)

Array original [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [90]:
# Reshape a 3x4
reshaped_ar = arr.reshape(5,4)
print("Array con nueva forma (5x4):")
print(reshaped_ar)

Array con nueva forma (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [92]:
# Cambiar la forma directamente
arr.shape = (4,5)
print("Array con forma cambiada (4x5):")
print(arr)

Array con forma cambiada (4x5):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
